### PR TITLE
fix breaking changes on zope.sqlalchemy 1.2

### PR DESCRIPTION
**Pull request by jordic**
Fixes breaking changes from here:
https://github.com/zopefoundation/zope.sqlalchemy/blob/master/CHANGES.rst

### CODE REVIEW

**Comment by dataflake** [comment]
This PR also mixes functional with a lot of cosmetic changes. Please do not do that, it makes reviewing hard!

**Review by mgedmin — APPROVED** [review]
Eh, LGTM.

**Review by icemac — APPROVED** [review]
LGTM.

**Review by dataflake — APPROVED** [review]

**Comment by mgedmin** [comment]
(The usual convention is that whoever opens the pull request gets to push the Merge button after receiving review approvals.)

**Comment by jordic** [comment]
Don't have permission O_O (no merge button)

**Comment by dataflake** [comment]
Can you look again? Something went wrong on the Plone Foundation side and they did not add you to any teams here. I added you to a team and that should give you access.

**Pull request merged**
